package com.relax.relax.common.constants;

public class SqlFieldType {
    public static final String BIGINT = " BIGINT";
    public static final String BINARY = " BINARY";
    public static final String BIT = " BIT";
    public static final String BLOB = " BLOB";
    public static final String CHAR = " CHAR";
    public static final String DATE = " DATE";
    public static final String DATETIME = " DATETIME";
    public static final String DECIMAL = " DECIMAL";
    public static final String DOUBLE = " DOUBLE";
    public static final String ENUM = " ENUM";
    public static final String FLOAT = " FLOAT";
    public static final String GEOMETRY = " GEOMETRY";
    public static final String GEOMETRYCOLLECTION = " GEOMETRYCOLLECTION";
    public static final String INT = " INT";
    public static final String INTEGER = " INTEGER";
    public static final String JSON = " JSON";
    public static final String LINESTRING = " LINESTRING";
    public static final String LONGBLOB = " LONGBLOB";
    public static final String LONGTEXT = " LONGTEXT";
    public static final String MEDIUMBLOB = " MEDIUMBLOB";
    public static final String MEDIUMINT = " MEDIUMINT";
    public static final String MEDIUMTEXT = " MEDIUMTEXT";
    public static final String MULTILINESTRING = " MULTILINESTRING";
    public static final String MULTIPOINT = " MULTIPOINT";
    public static final String MULTIPOLYGON = " MULTIPOLYGON";
    public static final String NUMERIC = " NUMERIC";
    public static final String POINT = " POINT";
    public static final String POLYGON = " POLYGON";
    public static final String REAL = " REAL";
    public static final String SET = " SET";
    public static final String SMALLINT = " SMALLINT";
    public static final String TEXT = " TEXT";
    public static final String TIME = " TIME";
    public static final String TIMESTAMP = " TIMESTAMP";
    public static final String TINYBLOB = " TINYBLOB";
    public static final String TINYINT = " TINYINT";
    public static final String TINYTEXT = " TINYTEXT";
    public static final String VARBINARY = " VARBINARY";
    public static final String VARCHAR = " VARCHAR";
    public static final String YEAR = " YEAR";
}
